// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BMfast
List BMfast(const arma::mat& X, const arma::colvec& y);
RcppExport SEXP LESYMAP_BMfast(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(BMfast(X, y));
    return rcpp_result_gen;
END_RCPP
}
// BMfast2
List BMfast2(const arma::mat& X, const arma::colvec& y, bool computeDOF);
RcppExport SEXP LESYMAP_BMfast2(SEXP XSEXP, SEXP ySEXP, SEXP computeDOFSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type computeDOF(computeDOFSEXP);
    rcpp_result_gen = Rcpp::wrap(BMfast2(X, y, computeDOF));
    return rcpp_result_gen;
END_RCPP
}
// regresfast
List regresfast(const arma::mat& X, const arma::colvec& y, const arma::mat& covariates, bool hascovar);
RcppExport SEXP LESYMAP_regresfast(SEXP XSEXP, SEXP ySEXP, SEXP covariatesSEXP, SEXP hascovarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< bool >::type hascovar(hascovarSEXP);
    rcpp_result_gen = Rcpp::wrap(regresfast(X, y, covariates, hascovar));
    return rcpp_result_gen;
END_RCPP
}
