# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Fast Brunner-Munzel tests (v2)
#'
#' @description
#' Takes a binary matrix of voxels and a vector of behavior
#' and runs Brunner-Munzel tests on each voxel.
#' This is a fast function that corrects for infinite values
#' with a similar approach as the nparcomp package.
#'
#' @param X binary matrix ov voxlels (columns) for all
#' subjects (rows)
#' @param y vector of behavioral scores.
#' @param computeDOF (true) chooses whether to compute degrees
#' of freedom. Set to false to save time during permutations.
#'
#' @return List with two vectors:
#' - statistic - BM values
#' - dfbm - degrees of freedom
#'
#' @author Dorian Pustina
#'
#' @export
BMfast2 <- function(X, y, computeDOF = TRUE) {
    .Call('LESYMAP_BMfast2', PACKAGE = 'LESYMAP', X, y, computeDOF)
}

#' @title Fast Brunner-Munzel tests (v1)
#'
#' @description
#' Takes a binary matrix of voxels and a vector of behavior
#' and runs Brunner-Munzel tests on each voxel.
#' This is a fast function, but may produce infinite values
#' for perfectly separated group. Use BMfast2 which avoids
#' this problem.
#'
#' @param X binary matrix ov voxlels (columns) for all
#' subjects (rows)
#' @param y vector of behavioral scores.
#'
#' @return List with two vectors:
#' - statistic - BM values
#' - dfbm - degrees of freedom
#'
#' @author Dorian Pustina
#'
#' @export
BMfast <- function(X, y) {
    .Call('LESYMAP_BMfast', PACKAGE = 'LESYMAP', X, y)
}

#' @title Fast linear regressions
#'
#' @description
#' Takes a matrix of voxels and a vector of behavior
#' and runs fast regressions for each voxel. Covariates
#' can be defined (i.e. age) to find the effect of each
#' voxel on behavior within the context of other predictive
#' factors.
#'
#' @param X matrix of voxlels (columns) for all
#' subjects (rows).
#' @param y vector of behavioral scores.
#' @param covariates matrix with one or more columns.
#' Must be of same length as behavior. This variable
#' should always be set, and the next argument can tell
#' if covariates should be used or not.
#' @param hascovar logical to tell whether covariates
#' should be used.
#'
#' @return List with (1) statistic, (2) n = number of
#' subjects, (3) kxfm = degrees of freedom.
#'
#' @author Dorian Pustina
#'
#' @export
regresfast <- function(X, y, covariates, hascovar = FALSE) {
    .Call('LESYMAP_regresfast', PACKAGE = 'LESYMAP', X, y, covariates, hascovar)
}

